<?php
/**
 * ChangeRequestApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Nopolabs\EBay\Commerce\Catalog
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Catalog API
 *
 * Use the Catalog API to search the eBay catalog for products on which to base a seller's item listing; to retrieve a product record by its eBay product identifier (ePID); to submit a catalog change request to modify an existing product or create a new product; and to manage catalog change requests.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Nopolabs\EBay\Commerce\Catalog;

use \Nopolabs\EBay\Commerce\Catalog\Configuration;
use \Nopolabs\EBay\Commerce\Catalog\ApiException;
use \Nopolabs\EBay\Commerce\Catalog\ObjectSerializer;

/**
 * ChangeRequestApiTest Class Doc Comment
 *
 * @category Class
 * @package  Nopolabs\EBay\Commerce\Catalog
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChangeRequestApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createChangeRequest
     *
     * .
     *
     */
    public function testCreateChangeRequest()
    {
    }

    /**
     * Test case for getChangeRequest
     *
     * .
     *
     */
    public function testGetChangeRequest()
    {
    }

    /**
     * Test case for getChangeRequests
     *
     * .
     *
     */
    public function testGetChangeRequests()
    {
    }
}
