<?php
/**
 * InventoryItemListingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nopolabs\EBay\Sell\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There is also a call in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: v1.6.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nopolabs\EBay\Sell\Inventory;

/**
 * InventoryItemListingTest Class Doc Comment
 *
 * @category    Class */
// * @description This type is used by the &lt;strong&gt;inventoryItems&lt;/strong&gt; container that is returned in the response of the &lt;strong&gt;bulkMigrateListing&lt;/strong&gt; call. Up to five &lt;strong&gt;sku&lt;/strong&gt;/&lt;strong&gt;offerId&lt;/strong&gt; pairs may be returned under the &lt;strong&gt;inventoryItems&lt;/strong&gt; container, dependent on how many eBay listings the seller is attempting to migrate to the inventory model.
/**
 * @package     Nopolabs\EBay\Sell\Inventory
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryItemListingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryItemListing"
     */
    public function testInventoryItemListing()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {
    }
}
