<?php
/**
 * ShippingServiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nopolabs\EBay\Sell\Account
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Account API
 *
 * The Account API gives sellers the ability to configure their eBay seller accounts, including the seller's policies (the Fulfillment Policy, Payment Policy, and Return Policy), opt in and out of eBay seller programs, configure sales tax tables, and get account information. For details on the restrictions and availability of the methods in this API, see API restrictions.
 *
 * OpenAPI spec version: v1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Nopolabs\EBay\Sell\Account;

/**
 * ShippingServiceTest Class Doc Comment
 *
 * @category    Class */
// * @description A complex type that defines the available shipping services offered in the parent &lt;b&gt;shippingOptions&lt;/b&gt; container. The shipping services specified here must be able to accommodate the &lt;b&gt;optionType&lt;/b&gt; defined in the parent &lt;b&gt;shippingOption&lt;/b&gt; container (either DOMESTIC or INTERNATIONAL). &lt;p class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt;Tip:&lt;/b&gt; For more on setting up shipping services, see &lt;a href&#x3D;\&quot;/api-docs/sell/static/seller-accounts/ht_shipping-free.html#shippingServices\&quot;&gt;Setting the shipping carrier and shipping service values&lt;/a&gt;.&lt;/p&gt;
/**
 * @package     Nopolabs\EBay\Sell\Account
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingService"
     */
    public function testShippingService()
    {
    }

    /**
     * Test attribute "additional_shipping_cost"
     */
    public function testPropertyAdditionalShippingCost()
    {
    }

    /**
     * Test attribute "buyer_responsible_for_pickup"
     */
    public function testPropertyBuyerResponsibleForPickup()
    {
    }

    /**
     * Test attribute "buyer_responsible_for_shipping"
     */
    public function testPropertyBuyerResponsibleForShipping()
    {
    }

    /**
     * Test attribute "cash_on_delivery_fee"
     */
    public function testPropertyCashOnDeliveryFee()
    {
    }

    /**
     * Test attribute "free_shipping"
     */
    public function testPropertyFreeShipping()
    {
    }

    /**
     * Test attribute "shipping_carrier_code"
     */
    public function testPropertyShippingCarrierCode()
    {
    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "shipping_service_code"
     */
    public function testPropertyShippingServiceCode()
    {
    }

    /**
     * Test attribute "ship_to_locations"
     */
    public function testPropertyShipToLocations()
    {
    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {
    }

    /**
     * Test attribute "surcharge"
     */
    public function testPropertySurcharge()
    {
    }
}
