{
  "swagger": "2.0",
  "info": {
    "description": "Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.",
    "version": "v1.6.0",
    "title": "Fulfillment API",
    "contact": {
      "name": "eBay Inc."
    },
    "license": {
      "name": "eBay API License Agreement",
      "url": "https://go.developer.ebay.com/api-license-agreement"
    }
  },
  "host": "api.ebay.com",
  "basePath": "/sell/fulfillment/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/order/{orderId}": {
      "get": {
        "tags": [
          "order"
        ],
        "summary": "Get an Order",
        "description": "Use this call to retrieve the contents of an order based on its unique identifier, orderId. This value was returned in the getOrders call's orders.orderId field when you searched for orders by creation date, modification date, or fulfillment status. The returned Order object contains information you can use to create and process fulfillments, including: Information about the buyer and seller Information about the order's line items The plans for packaging, addressing and [...]",
        "operationId": "getOrder",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment",
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly"
            ]
          }
        ]
      }
    },
    "/order": {
      "get": {
        "tags": [
          "order"
        ],
        "summary": "Get Orders",
        "description": "Use this call to search for and retrieve one or more orders based on their creation date, last modification date, or fulfillment status using the filter parameter. You can alternatively specify a list of orders using the orderIds parameter. The returned Order objects contain information you can use to create and process fulfillments, including: Information about the buyer and seller Information about the order's line items The plans for packaging, addressing and shipping [...]",
        "operationId": "getOrders",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment",
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly"
            ]
          }
        ]
      }
    },
    "/order/{orderId}/shipping_fulfillment": {
      "get": {
        "tags": [
          "shipping_fulfillment"
        ],
        "summary": "Get Shipping Fulfillments",
        "description": "Use this call to retrieve the contents of all fulfillments currently defined for a specified order based on the order's unique identifier, orderId. This value is returned in the getOrders call's members.orderId field when you search for orders by creation date or shipment status.",
        "operationId": "getShippingFulfillments",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment",
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "shipping_fulfillment"
        ],
        "summary": "Create a Shipping Fulfillment",
        "description": "When you group an order's line items into one or more packages, each package requires a corresponding plan for handling, addressing, and shipping; this is a shipping fulfillment. For each package, execute this call once to generate a shipping fulfillment associated with that package. Note: A single line item in an order can consist of multiple units of a purchased item, and one unit can consist of multiple parts or components. Although these components might be provided b[...]",
        "operationId": "createShippingFulfillment",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment"
            ]
          }
        ]
      }
    },
    "/order/{orderId}/shipping_fulfillment/{fulfillmentId}": {
      "get": {
        "tags": [
          "shipping_fulfillment"
        ],
        "summary": "Get a Shipping Fulfillment",
        "description": "Use this call to retrieve the contents of a fulfillment based on its unique identifier, fulfillmentId (combined with the associated order's orderId). The fulfillmentId value was originally generated by the createShippingFulfillment call, and is returned by the getShippingFulfillments call in the members.fulfillmentId field.",
        "operationId": "getShippingFulfillment",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment",
              "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "Authorization Code": {
      "description": "The security definitions for this API. Please check individual operations for applicable scopes.",
      "type": "oauth2",
      "authorizationUrl": "https://auth.ebay.com/oauth2/authorize",
      "tokenUrl": "https://api.ebay.com/identity/v1/oauth2/token",
      "flow": "accessCode",
      "scopes": {
        "https://api.ebay.com/oauth/api_scope/sell.fulfillment": "View and manage your order fulfillments",
        "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly": "View your order fulfillments"
      }
    }
  }
}