{
  "swagger": "2.0",
  "info": {
    "description": "The Marketing API offers two platforms that let sellers promote and advertise their products: Promoted Listings is an eBay ad service that lets sellers set up ad campaigns for the products they want to promote. eBay displays the ads in search results and in other marketing modules as SPONSORED listings. If an item in a Promoted Listings campaign sells, the seller is assessed a Promoted Listings fee, which is a seller-specified percentage of the sales price. For complete detai[...]",
    "version": "v1.4.0",
    "title": "Marketing API",
    "contact": {
      "name": "eBay Inc,"
    },
    "license": {
      "name": "eBay API License Agreement",
      "url": "https://go.developer.ebay.com/api-license-agreement"
    }
  },
  "host": "api.ebay.com",
  "basePath": "/sell/marketing/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/ad_campaign/{campaign_id}/bulk_create_ads_by_inventory_reference": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method creates an ad for each inventory reference ID specified in the request and associates the newly created ads with the specified campaign. Use the campaign ID returned from createCampaign as a URI parameter in your call to this method. In the payload, specify the bidPercentage, inventoryReferenceId, and inventoryReferenceType for each listing you want to include in the campaign. Each listing you specify becomes a new ad that is associated with the campaign. An i[...]",
        "operationId": "bulkCreateAdsByInventoryReference",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/bulk_create_ads_by_listing_id": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method creates an ad for each listing ID specified in the request and associates the newly created ads with the specified campaign. Use the campaign ID returned from createCampaign as a URI parameter and specify a list of elements, each containing a listingId and its associated bidPercentage, for each listing you want associated with the ad campaign. Each listing you specify becomes a new ad that is associated with the campaign. A listing ID can be either a listing I[...]",
        "operationId": "bulkCreateAdsByListingId",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/bulk_delete_ads_by_inventory_reference": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method deletes a set of ads, as specified by a list of inventory reference IDs, from the specified campaign. Pass the campaign_id as a URI parameter and create a request payload that contains a list of inventoryReferenceId and inventoryReferenceType pairs. An inventory reference ID is either a seller-defined SKU value or an inventoryItemGroupKey (a seller-defined ID for an inventory item group, which is an entity that's used in the Inventory API to create a multiple-[...]",
        "operationId": "bulkDeleteAdsByInventoryReference",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/bulk_delete_ads_by_listing_id": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method deletes a set of ads, as specified by a list of listing IDs, from the specified campaign. Supply the campaign_id as a URI parameter and create a request payload that contains a list of listingId values. An eBay listing ID is generated when a listing is created on eBay. Get the campaign IDs for a seller by calling getCampaigns and call getAds to get a list of the seller's listing IDs. Note: This request accepts both listing IDs, as generated by the Inventory AP[...]",
        "operationId": "bulkDeleteAdsByListingId",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/bulk_update_ads_bid_by_inventory_reference": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method replaces an ad bid based on a list of inventory references IDs associated with the specified campaign. In the request, specify the campaign_id as a URI parameter and a list of the bidPercentage, inventoryReferenceId, inventoryReferenceType fields. An inventory reference ID is either a seller-defined SKU value or an inventoryItemGroupKey (a seller-defined ID for an inventory item group, which is an entity that's used in the Inventory API to create a multiple-va[...]",
        "operationId": "bulkUpdateAdsBidByInventoryReference",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/bulk_update_ads_bid_by_listing_id": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method replaces an ad bid based on a supplied list of listing IDs that are associated with the specified campaign. In the request, specify the campaign_id as a URI parameter and create a request payload that contains a list of listingId values. An eBay listing ID is generated when a listing is created on eBay. Get the campaign IDs for a seller by calling getCampaigns and call getAds to get a list of the seller's listing IDs. Note: This request accepts both listing ID[...]",
        "operationId": "bulkUpdateAdsBidByListingId",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/ad": {
      "get": {
        "tags": [
          "ad"
        ],
        "description": "This method retrieves all the ads for the specified campaign. Use the listing_ids query parameter to control the ads to target, and paginate the result set by specifying a limit, which dictates how many ads to return on each page of the response. Specify how many ads to skip in the result set before returning the first result using the offset parameter. Call getCampaigns to retrieve the current campaign IDs for the seller. Note: This field accepts both a listingId, as gen[...]",
        "operationId": "getAds",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method creates an ad for the specified listing ID, sets the bid percentage for that specific item, and associates the ad with the specified campaign. Use the campaign ID returned from createCampaign as a URI parameter and specify a listingId and its associated bidPercentage in the payload. After processing the request, eBay returns the ID of the newly-created ad in the Location response header. Call getCampaigns to get a list of the seller's campaign IDs. Note: This [...]",
        "operationId": "createAdByListingId",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/create_ads_by_inventory_reference": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method creates an ad for the specified inventory reference ID, sets the bid percentage for that specific item, and associates the ad with the specified campaign. Use the campaign ID returned from createCampaign as a URI parameter and in the payload specify an inventoryReferenceId, its inventoryReferenceType, and the bidPercentage for the specific item. After processing the request, eBay returns the ID of the newly-created ad in the Location response header. Note: If [...]",
        "operationId": "createAdsByInventoryReference",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/ad/{ad_id}": {
      "get": {
        "tags": [
          "ad"
        ],
        "description": "This method retrieves the specified ad from the specified campaign. In the request, supply the campaign_id and ad_id as URI parameters. Call getCampaigns to retrieve a list of the seller's current campaign IDs and call getAds to retrieve their current ad IDs.",
        "operationId": "getAd",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ad"
        ],
        "description": "This method removes the specified ad from the specified campaign. This method requires that you pass in the ID of the ad to delete and the ID of the campaign to which the ad is associated. Call getCampaigns to get the current list of the seller's campaign IDs.",
        "operationId": "deleteAd",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/delete_ads_by_inventory_reference": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method deletes ads using a list of seller inventory reference IDs that are associated with the specified campaign ID. Specify the campaign ID and a list of inventoryReferenceId and inventoryReferenceType pairs to be deleted. Call getCampaigns to get a list of the seller's current campaign IDs.",
        "operationId": "deleteAdsByInventoryReference",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/get_ads_by_inventory_reference": {
      "get": {
        "tags": [
          "ad"
        ],
        "description": "This method retrieves ads from the specified campaign using the seller's inventory reference ID and inventory reference type. Supply the campaign_id as a URI parameter and configure the payload with inventory_reference_id inventory_reference_type pairs. An inventory reference ID is either a seller-defined SKU value or an inventoryItemGroupKey (a seller-defined ID for an inventory item group, which is an entity that's used in the Inventory API to create a multiple-variatio[...]",
        "operationId": "getAdsByInventoryReference",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/ad/{ad_id}/update_bid": {
      "post": {
        "tags": [
          "ad"
        ],
        "description": "This method updates the bid for the specified ad in the specified campaign. In the request, supply the campaign_id and ad_id as a URI parameters. Call getCampaigns to retrive a seller's current campaign IDs and call getAds to get their ad IDs.",
        "operationId": "updateBid",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/clone": {
      "post": {
        "tags": [
          "campaign"
        ],
        "description": "This method clones (makes a copy of) the specified campaign. Supply the campaign_id as a URI parameter. The ID of the newly-cloned campaign is returned in the Location response header. Call getCampaigns to retrieve a seller's current campaign IDs Requirement: In order to clone a campaign, the campaignStatus must be ENDED and the campaign must define a set of selection rules (it must be a rules-based campaign).",
        "operationId": "cloneCampaign",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign": {
      "get": {
        "tags": [
          "campaign"
        ],
        "description": "This method retrieves the details for all the campaigns of a seller, including the campaign's the selection rules. Note that this method does not return the listing IDs or inventory reference IDs of the items included in the ad campaign. Call getAds to retrieve these IDs. You can filter the result set by a campaign name, end date range, start date range, or campaign status. You can also paginate the records returned from the result set using the limit query parameter, and[...]",
        "operationId": "getCampaigns",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "campaign"
        ],
        "description": "This method creates a Promoted Listings ad campaign. To create a basic campaign, supply the user-defined campaign name, the start date (and optionally the end date) of the campaign, the eBay marketplace on which the campaign is hosted, and details on the campaign funding model. The campaign funding model specifies how the Promoted Listings fee is calculated. Currently, the only supported funding model is COST_PER_SALE. For complete information on how the fee is calculated[...]",
        "operationId": "createCampaign",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}": {
      "get": {
        "tags": [
          "campaign"
        ],
        "description": "This method retrieves the details of a single campaign, as specified with the campaign_id query parameter. This method returns all the details of a campaign (including the campaign's the selection rules), except the for the listing IDs or inventory reference IDs included in the campaign. These IDs are returned by getAds. Call getCampaigns to retrieve a list of the seller's campaign IDs. Note: This call does not retrieve campaigns created via the eBay web flow.",
        "operationId": "getCampaign",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "campaign"
        ],
        "description": "This method deletes the campaign specified by the campaign_id query parameter. Note: You can delete only campaigns that have ended. Call getCampaigns to retrieve the campaign_id and the campaign status (RUNNING, PAUSED, ENDED, and so on) for all the seller's campaigns.",
        "operationId": "deleteCampaign",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/end": {
      "post": {
        "tags": [
          "campaign"
        ],
        "description": "This method ends an active (RUNNINGM) or paused campaign. Specify the campaign you want to end by supplying its campaign ID in a query parameter. Call getCampaigns to retrieve the campaign_id and the campaign status (RUNNING, PAUSED, ENDED, and so on) for all the seller's campaigns.",
        "operationId": "endCampaign",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/find_campaign_by_ad_reference": {
      "get": {
        "tags": [
          "campaign"
        ],
        "description": "This method retrieves the campaign containing the listing that is specified using either an eBay listing ID or an inventory reference ID and inventory reference type. eBay listing IDs are generated when you create a listing. An inventory reference ID can be either a seller-defined SKU value or an inventoryItemGroupKey (a seller-defined ID for an inventory item group, which is an entity that's used by the Inventory API to create a multiple-variation listing such as a shirt[...]",
        "operationId": "findCampaignByAdReference",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/get_campaign_by_name": {
      "get": {
        "tags": [
          "campaign"
        ],
        "description": "This method retrieves the details of a single campaign, as specified with the campaign_name query parameter. Note that the campaign name you specify must be an exact, case-sensitive match of the name of the campaign you want to retrieve. This method returns all the details of a campaign (including the campaign's the selection rules), except the for the listing IDs or inventory reference IDs included in the campaign. These IDs are returned by getAds. Call getCampaigns to r[...]",
        "operationId": "getCampaignByName",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/pause": {
      "post": {
        "tags": [
          "campaign"
        ],
        "description": "This method pauses an active (RUNNING) campaign. You can restarted by calling resumeCampaign, as long as the campaign's end date is in the future. Note: The listings associated with a paused campaign cannot be added into another campaign. Call getCampaigns to retrieve the campaign_id and the campaign status (RUNNING, PAUSED, ENDED, and so on) for all the seller's campaigns.",
        "operationId": "pauseCampaign",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/resume": {
      "post": {
        "tags": [
          "campaign"
        ],
        "description": "This method resumes a paused campaign, as long as it's end date is in the future. Supply the campaign_id for the campaign you want to restart as a query parameter in the request. Call getCampaigns to retrieve the campaign_id and the campaign status (RUNNING, PAUSED, ENDED, and so on) for all the seller's campaigns.",
        "operationId": "resumeCampaign",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_campaign/{campaign_id}/update_campaign_identification": {
      "post": {
        "tags": [
          "campaign"
        ],
        "description": "This method replaces the name and the start and end dates of a campaign. Specify the campaign_id you want to update as a URI parameter, and configure the campaignName and startDate in the request payload. If you want to change only the end date of the campaign, specify the current campaign name and set startDate to the current date (you cannot use a start date that is in the past), and set the endDate as desired. Note that if you do not set a new end date in this call, an[...]",
        "operationId": "updateCampaignIdentification",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_report/{report_id}": {
      "get": {
        "tags": [
          "ad_report"
        ],
        "description": "This call downloads the report as specified by the report_id path parameter. Note: All date values are returned in UTC format (yyyy-MM-ddThh:mm:ss.sssZ), which you can convert and display in the seller's local time.",
        "operationId": "getReport",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_report_metadata": {
      "get": {
        "tags": [
          "ad_report_metadata"
        ],
        "description": "This call retrieves information that details the fields used in each of the Promoted Listings reports. The request for this method does not use a payload or any URI parameters. Use the information returned by this method to configure the different Promoted Listings report types.",
        "operationId": "getReportMetadata",
        "security": [
          {
            "Client Credentials": [
              "https://api.ebay.com/oauth/api_scope"
            ]
          }
        ]
      }
    },
    "/ad_report_metadata/{report_type}": {
      "get": {
        "tags": [
          "ad_report_metadata"
        ],
        "description": "This call retrieves metadata that details the fields used by the Promoted Listings report type that's specified by the report_type path parameter. This method does not use a request payload. Use the information returned by this method to configure the specified Promoted Listings report.",
        "operationId": "getReportMetadataForReportType",
        "security": [
          {
            "Client Credentials": [
              "https://api.ebay.com/oauth/api_scope"
            ]
          }
        ]
      }
    },
    "/ad_report_task": {
      "get": {
        "tags": [
          "ad_report_task"
        ],
        "description": "This method returns information on all the existing report tasks related to a seller. Use the report_task_statuses query parameter to control which reports to return. You can paginate the result set by specifying a limit, which dictates how many report tasks to return on each page of the response. Use the offset parameter to specify how many reports to skip in the result set before returning the first result.",
        "operationId": "getReportTasks",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ad_report_task"
        ],
        "description": "This method creates a report task, which generates a Promoted Listings report based on the values specified in the call. The report is generated based on the criteria you specify, including the report type, the report's dimensions and metrics, the report's start and end dates, the listings to include in the report, and more. Metrics are the quantitative measurements in the report while dimensions specify the attributes of the data included in the reports. For details on t[...]",
        "operationId": "createReportTask",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/ad_report_task/{report_task_id}": {
      "get": {
        "tags": [
          "ad_report_task"
        ],
        "description": "This call returns the details of a specific Promoted Listings report task, as specified by the report_task_id path parameter. The report task includes the report criteria (such as the report dimensions, metrics, and included listing) and the report-generation rules (such as starting and ending dates for the specified report task). Report-task IDs are generated by eBay when you call createReportTask. Get a complete list of a seller's report-task IDs by calling getReportTas[...]",
        "operationId": "getReportTask",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ad_report_task"
        ],
        "description": "This call deletes the report task specified by the report_task_id path parameter. This method also deletes any reports generated by the report task. Report task IDs are generated by eBay when you call createReportTask. Get a complete list of a seller's report-task IDs by calling getReportTasks.",
        "operationId": "deleteReportTask",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/item_price_markdown": {
      "post": {
        "tags": [
          "item_price_markdown"
        ],
        "description": "This method creates an item price markdown promotion (know simply as a &quot;markdown promotion&quot;) where a discount amount is applied directly to the items included the promotion. Discounts can be specified as either a monetary amount or a percentage off the standard sales price. eBay highlights promoted items by placing teasers for the items throughout the online sales flows. Unlike an item promotion, a markdown promotion does not require the buyer meet a &quot;thres[...]",
        "operationId": "createItemPriceMarkdownPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/item_price_markdown/{promotion_id}": {
      "get": {
        "tags": [
          "item_price_markdown"
        ],
        "description": "This method returns the complete details of the item price markdown promotion that's indicated by the promotion_id path parameter. Call getPromotions to retrieve the IDs of a seller's promotions.",
        "operationId": "getItemPriceMarkdownPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "item_price_markdown"
        ],
        "description": "This method updates the specified item price markdown promotion with the new configuration that you supply in the payload of the request. Specify the promotion you want to update using the promotion_id path parameter. Call getPromotions to retrieve the IDs of a seller's promotions. When updating a promotion, supply all the fields that you used to configure the original promotion (and not just the fields you are updating). eBay replaces the specified promotion with the val[...]",
        "operationId": "updateItemPriceMarkdownPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "item_price_markdown"
        ],
        "description": "This method deletes the item price markdown promotion specified by the promotion_id path parameter. Call getPromotions to retrieve the IDs of a seller's promotions. You can delete any promotion with the exception of those that are currently active (RUNNING). To end a running promotion, call updateItemPriceMarkdownPromotion and adjust the endDate field as appropriate.",
        "operationId": "deleteItemPriceMarkdownPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/item_promotion": {
      "post": {
        "tags": [
          "item_promotion"
        ],
        "description": "This method creates an item promotion (known casually as a &quot;threshold promotion&quot;) where the buyer receives a discount benefit when they meet the buying criteria that is set for the promotion. Discounts can be specified as either a monetary amount or a percentage off the standard sales price, giving you the ability offer discounts such as &quot;Buy 1 Get 1&quot;, or &quot;Buy $50, get 20% off&quot;. eBay highlights promoted items by placing teasers for the items [...]",
        "operationId": "createItemPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/item_promotion/{promotion_id}": {
      "get": {
        "tags": [
          "item_promotion"
        ],
        "description": "This method returns the complete details of the threshold promotion specified by the promotion_id path parameter. Call getPromotions to retrieve the IDs of a seller's promotions.",
        "operationId": "getItemPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "item_promotion"
        ],
        "description": "This method updates the specified threshold promotion with the new configuration that you supply in the request. Indicate the promotion you want to update using the promotion_id path parameter. Call getPromotions to retrieve the IDs of a seller's promotions. When updating a promotion, supply all the fields that you used to configure the original promotion (and not just the fields you are updating). eBay replaces the specified promotion with the values you supply in the up[...]",
        "operationId": "updateItemPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "item_promotion"
        ],
        "description": "This method deletes the threshold promotion specified by the promotion_id path parameter. Call getPromotions to retrieve the IDs of a seller's promotions. You can delete any promotion with the exception of those that are currently active (RUNNING). To end a running threshold promotion, call updateItemPromotion and adjust the endDate field as appropriate.",
        "operationId": "deleteItemPromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/promotion/{promotion_id}/get_listing_set": {
      "get": {
        "tags": [
          "promotion"
        ],
        "description": "This method returns the set of listings associated with the promotion_id specified in the path parameter. Call getPromotions to retrieve the IDs of a seller's promotions. The listing details are returned in a paginated set and you can control and results returned using the following query parameters: limit, offset, q, sort, and status. Maximum associated listings returned: 200 Default number of listings returned: 200",
        "operationId": "getListingSet",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/promotion": {
      "get": {
        "tags": [
          "promotion"
        ],
        "description": "This method returns a list of a seller's undeleted promotions. The call returns up to 200 currently-available promotions on the specified marketplace. While the response body does not include the promotion's discountRules or inventoryCriterion containers, it does include the promotionHref (which you can use to retrieve the complete details of the promotion). Use query parameters to sort and filter the results by the number of promotions to return, the promotion state, and[...]",
        "operationId": "getPromotions",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/promotion/{promotion_id}/pause": {
      "post": {
        "tags": [
          "promotion"
        ],
        "description": "This method pauses a currently-active (RUNNING) threshold promotion and changes the state of the promotion from RUNNING to PAUSED. Pausing a promotion makes the promotion temporarily unavailable to buyers and any currently-incomplete transactions will not receive the promotional offer until the promotion is resumed. Also, promotion teasers are not displayed when a promotion is paused. Pass the ID of the promotion you want to pause using the promotion_id path parameter. Ca[...]",
        "operationId": "pausePromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/promotion/{promotion_id}/resume": {
      "post": {
        "tags": [
          "promotion"
        ],
        "description": "This method restarts a threshold promotion that was previously paused and changes the state of the promotion from PAUSED to RUNNING. Only promotions that have been previously paused can be resumed. Resuming a promotion reinstates the promotional teasers and any transactions that were in motion before the promotion was paused will again be eligible for the promotion. Pass the ID of the promotion you want to resume using the promotion_id path parameter. Call getPromotions t[...]",
        "operationId": "resumePromotion",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/promotion_report": {
      "get": {
        "tags": [
          "promotion_report"
        ],
        "description": "This method generates a report that lists the seller's running, paused, and ended promotions for the specified eBay marketplace. The result set can be filtered by the promotion status and the number of results to return. You can also supply keywords to limit the report to promotions that contain the specified keywords. Specify the eBay marketplace for which you want the report run using the marketplace_id query parameter. Supply additional query parameters to control the [...]",
        "operationId": "getPromotionReports",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    },
    "/promotion_summary_report": {
      "get": {
        "tags": [
          "promotion_summary_report"
        ],
        "description": "This method generates a report that summarizes the seller's promotions for the specified eBay marketplace. The report returns information on RUNNING, PAUSED, and ENDED promotions (deleted reports are not returned) and summarizes the seller's campaign performance for all promotions on a given site. For information about summary reports, see Reading the item promotion Summary report.",
        "operationId": "getPromotionSummaryReport",
        "security": [
          {
            "Authorization Code": [
              "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly",
              "https://api.ebay.com/oauth/api_scope/sell.marketing"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "Authorization Code": {
      "description": "The security definitions for this API. Please check individual operations for applicable scopes.",
      "type": "oauth2",
      "authorizationUrl": "https://auth.ebay.com/oauth2/authorize",
      "tokenUrl": "https://api.ebay.com/identity/v1/oauth2/token",
      "flow": "accessCode",
      "scopes": {
        "https://api.ebay.com/oauth/api_scope/sell.marketing.readonly": "View your eBay marketing activities, such as ad campaigns and listing promotions",
        "https://api.ebay.com/oauth/api_scope/sell.marketing": "View and manage your eBay marketing activities, such as ad campaigns and listing promotions"
      }
    },
    "Client Credentials": {
      "description": "The security definitions for this API. Please check individual operations for applicable scopes.",
      "type": "oauth2",
      "tokenUrl": "https://api.ebay.com/identity/v1/oauth2/token",
      "flow": "application",
      "scopes": {
        "https://api.ebay.com/oauth/api_scope": "View public data from eBay"
      }
    }
  }
}